import 'dart:io';

import 'package:archive/archive_io.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:memex/data/services/asset_safety_service.dart';
import 'package:memex/data/services/document_text_extraction_service.dart';
import 'package:memex/data/services/file_system_service.dart';
import 'package:memex/utils/logger.dart';
import 'package:memex/utils/user_storage.dart';
import 'package:path/path.dart' as p;

enum ImportedGeneratedFileKind {
  extractedText,
  assetReference,
}

class ImportedFileRecord {
  const ImportedFileRecord({
    required this.relativePath,
    required this.sizeBytes,
    this.generatedKind,
    this.sourceRelativePath,
  });

  /// Path relative to the user's workspace root.
  final String relativePath;
  final int sizeBytes;

  /// Kind of helper file generated by Memex during import.
  final ImportedGeneratedFileKind? generatedKind;

  /// True when Memex generated this helper file during import.
  bool get isGenerated => generatedKind != null;

  /// Original imported file that this helper file was generated from.
  final String? sourceRelativePath;
}

class FileImportResult {
  const FileImportResult({
    required this.sourceName,
    required this.settingsRelativeDirectoryPath,
    required this.workspaceRelativeDirectoryPath,
    required this.absoluteDirectoryPath,
    required this.files,
    required this.renamedConflictCount,
    required this.skippedUnsafeArchiveEntries,
  });

  final String sourceName;

  /// Path relative to `/_UserSettings`, e.g. `Imported/My Export`.
  final String settingsRelativeDirectoryPath;

  /// Path relative to the workspace, e.g.
  /// `_UserSettings/Imported/My Export`.
  final String workspaceRelativeDirectoryPath;
  final String absoluteDirectoryPath;
  final List<ImportedFileRecord> files;
  final int renamedConflictCount;
  final int skippedUnsafeArchiveEntries;

  int get importedFileCount => files.where((file) => !file.isGenerated).length;

  int get generatedTextFileCount => files
      .where((file) =>
          file.generatedKind == ImportedGeneratedFileKind.extractedText)
      .length;

  int get generatedAssetReferenceFileCount => files
      .where((file) =>
          file.generatedKind == ImportedGeneratedFileKind.assetReference)
      .length;
}

typedef ImportedDocumentTextExtractor = Future<String?> Function(File file);

class FileImportService {
  FileImportService._({
    ImportedDocumentTextExtractor? extractDocumentText,
  }) : _extractDocumentText = extractDocumentText ??
            DocumentTextExtractionService.instance.extractForAgent;

  static final FileImportService instance = FileImportService._();

  @visibleForTesting
  factory FileImportService.forTesting({
    ImportedDocumentTextExtractor? extractDocumentText,
  }) {
    return FileImportService._(
      extractDocumentText: extractDocumentText,
    );
  }

  final ImportedDocumentTextExtractor _extractDocumentText;
  final _logger = getLogger('FileImportService');

  Future<FileImportResult> importToUserSettingsImported(
    List<String> sourcePaths, {
    void Function(String status)? onProgress,
  }) async {
    final userId = await UserStorage.getUserId();
    if (userId == null || userId.isEmpty) {
      throw StateError('User not logged in');
    }
    if (sourcePaths.isEmpty) {
      throw ArgumentError('No source files selected');
    }

    final existingSources = <File>[];
    for (final sourcePath in sourcePaths) {
      final file = File(sourcePath);
      if (await file.exists()) {
        existingSources.add(file);
      }
    }
    if (existingSources.isEmpty) {
      throw ArgumentError('No readable source files selected');
    }

    final fs = FileSystemService.instance;
    final workspaceRoot = fs.getWorkspacePath(userId);
    final settingsRoot = fs.getUserSettingsPath(userId);
    final importRoot = fs.getImportedFilesPath(userId);
    final importRootDir = Directory(importRoot);
    if (!await importRootDir.exists()) {
      await importRootDir.create(recursive: true);
    }

    final sourceName = _sourceNameFor(existingSources);
    final targetDir = await _uniqueDirectory(importRoot, sourceName);
    final targetDirPath = targetDir.path;
    final renamedRootConflict = p.basename(targetDirPath) != sourceName;

    onProgress?.call('Importing files...');
    final files = <ImportedFileRecord>[];
    var renamedConflicts = renamedRootConflict ? 1 : 0;
    var skippedUnsafeEntries = 0;

    for (final source in existingSources) {
      if (_isZip(source.path)) {
        final result = await _extractZipSource(
          source,
          targetDirPath,
          workspaceRoot,
          userId: userId,
          nestedDirectory: existingSources.length > 1,
        );
        files.addAll(result.files);
        renamedConflicts += result.renamedConflictCount;
        skippedUnsafeEntries += result.skippedUnsafeArchiveEntries;
      } else {
        final result = await _copyFileSource(
          source,
          targetDirPath,
          workspaceRoot,
          userId,
        );
        files.addAll(result.files);
        if (result.wasRenamed) renamedConflicts += 1;
      }
    }

    final settingsRelative = p.relative(targetDirPath, from: settingsRoot);
    final workspaceRelative = p.relative(targetDirPath, from: workspaceRoot);
    return FileImportResult(
      sourceName: p.basename(targetDirPath),
      settingsRelativeDirectoryPath: settingsRelative,
      workspaceRelativeDirectoryPath: workspaceRelative,
      absoluteDirectoryPath: targetDirPath,
      files: List<ImportedFileRecord>.unmodifiable(files),
      renamedConflictCount: renamedConflicts,
      skippedUnsafeArchiveEntries: skippedUnsafeEntries,
    );
  }

  Future<_CopyResult> _copyFileSource(
    File source,
    String targetDirPath,
    String workspaceRoot,
    String userId,
  ) async {
    final desiredPath = p.join(targetDirPath, p.basename(source.path));
    final targetPath = await _uniqueFilePath(desiredPath);
    await Directory(p.dirname(targetPath)).create(recursive: true);
    await source.copy(targetPath);
    final stat = await File(targetPath).stat();
    final importedFile = ImportedFileRecord(
      relativePath: p.relative(targetPath, from: workspaceRoot),
      sizeBytes: stat.size,
    );
    final files = <ImportedFileRecord>[importedFile];
    final extractedTextFile = await _createExtractedTextFile(
      File(targetPath),
      workspaceRoot: workspaceRoot,
      sourceRelativePath: importedFile.relativePath,
    );
    if (extractedTextFile != null) {
      files.add(extractedTextFile);
    }
    final assetReferenceFile = await _createAssetReferenceFile(
      File(targetPath),
      workspaceRoot: workspaceRoot,
      userId: userId,
      sourceRelativePath: importedFile.relativePath,
    );
    if (assetReferenceFile != null) {
      files.add(assetReferenceFile);
    }
    return _CopyResult(
      files: files,
      wasRenamed: p.normalize(targetPath) != p.normalize(desiredPath),
    );
  }

  Future<_ZipExtractResult> _extractZipSource(
    File source,
    String targetDirPath,
    String workspaceRoot, {
    required String userId,
    required bool nestedDirectory,
  }) async {
    final archive = ZipDecoder().decodeBytes(await source.readAsBytes());
    final baseTargetDir = nestedDirectory
        ? (await _uniqueDirectory(
            targetDirPath,
            _sanitizePathSegment(p.basenameWithoutExtension(source.path)),
          ))
            .path
        : targetDirPath;

    final files = <ImportedFileRecord>[];
    var renamedConflicts = nestedDirectory &&
            p.basename(baseTargetDir) !=
                _sanitizePathSegment(p.basenameWithoutExtension(source.path))
        ? 1
        : 0;
    var skippedUnsafeEntries = 0;

    for (final entry in archive.files) {
      final entryPath = _safeArchiveEntryPath(entry.name);
      if (entryPath == null) {
        skippedUnsafeEntries += 1;
        continue;
      }

      final targetPath = p.normalize(p.join(baseTargetDir, entryPath));
      if (!_isPathWithin(baseTargetDir, targetPath)) {
        skippedUnsafeEntries += 1;
        continue;
      }

      if (!entry.isFile) {
        await Directory(targetPath).create(recursive: true);
        continue;
      }

      final uniqueTargetPath = await _uniqueFilePath(targetPath);
      if (p.normalize(uniqueTargetPath) != p.normalize(targetPath)) {
        renamedConflicts += 1;
      }
      await Directory(p.dirname(uniqueTargetPath)).create(recursive: true);
      final output = OutputFileStream(uniqueTargetPath);
      try {
        entry.writeContent(output);
      } finally {
        output.closeSync();
      }
      final stat = await File(uniqueTargetPath).stat();
      final importedFile = ImportedFileRecord(
        relativePath: p.relative(uniqueTargetPath, from: workspaceRoot),
        sizeBytes: stat.size,
      );
      files.add(importedFile);
      final extractedTextFile = await _createExtractedTextFile(
        File(uniqueTargetPath),
        workspaceRoot: workspaceRoot,
        sourceRelativePath: importedFile.relativePath,
      );
      if (extractedTextFile != null) {
        files.add(extractedTextFile);
      }
      final assetReferenceFile = await _createAssetReferenceFile(
        File(uniqueTargetPath),
        workspaceRoot: workspaceRoot,
        userId: userId,
        sourceRelativePath: importedFile.relativePath,
      );
      if (assetReferenceFile != null) {
        files.add(assetReferenceFile);
      }
    }

    return _ZipExtractResult(
      files: files,
      renamedConflictCount: renamedConflicts,
      skippedUnsafeArchiveEntries: skippedUnsafeEntries,
    );
  }

  static bool _isZip(String filePath) =>
      p.extension(filePath).toLowerCase() == '.zip';

  Future<ImportedFileRecord?> _createExtractedTextFile(
    File importedFile, {
    required String workspaceRoot,
    required String sourceRelativePath,
  }) async {
    final extractedText = await _extractDocumentText(importedFile);
    if (extractedText == null) return null;

    final desiredPath = p.join(
      p.dirname(importedFile.path),
      '${p.basename(importedFile.path)}.extracted-text-for-agent.md',
    );
    final targetPath = await _uniqueFilePath(desiredPath);
    await File(targetPath).writeAsString(extractedText);
    final stat = await File(targetPath).stat();
    return ImportedFileRecord(
      relativePath: p.relative(targetPath, from: workspaceRoot),
      sizeBytes: stat.size,
      generatedKind: ImportedGeneratedFileKind.extractedText,
      sourceRelativePath: sourceRelativePath,
    );
  }

  Future<ImportedFileRecord?> _createAssetReferenceFile(
    File importedFile, {
    required String workspaceRoot,
    required String userId,
    required String sourceRelativePath,
  }) async {
    final assetType = _assetTypeForPath(importedFile.path);
    if (assetType == null) return null;

    try {
      final (fileName, assetRelativePath) =
          await FileSystemService.instance.saveAssetFromFile(
        userId: userId,
        sourcePath: importedFile.path,
        assetType: assetType,
      );
      final fsReference = 'fs://$fileName';
      final helperContent = _buildAssetReferenceHelperContent(
        fsReference: fsReference,
      );
      final desiredPath = p.join(
        p.dirname(importedFile.path),
        '${p.basename(importedFile.path)}.asset-reference-for-agent.md',
      );
      final targetPath = await _uniqueFilePath(desiredPath);
      await File(targetPath).writeAsString(helperContent);
      final stat = await File(targetPath).stat();
      return ImportedFileRecord(
        relativePath: p.relative(targetPath, from: workspaceRoot),
        sizeBytes: stat.size,
        generatedKind: ImportedGeneratedFileKind.assetReference,
        sourceRelativePath: sourceRelativePath,
      );
    } catch (e, st) {
      _logger.warning(
        'Failed to create asset reference helper for ${importedFile.path}',
        e,
        st,
      );
      return null;
    }
  }

  static String? _assetTypeForPath(String filePath) {
    final extension = p.extension(filePath).toLowerCase();
    if (AssetSafetyService.imageExtensions.contains(extension)) {
      return 'img';
    }
    return null;
  }

  String _buildAssetReferenceHelperContent({
    required String fsReference,
  }) {
    return 'Corresponding `fs://` reference: `$fsReference`\n';
  }

  static String _sourceNameFor(List<File> sources) {
    if (sources.length == 1) {
      final source = sources.single.path;
      final stem = _isZip(source)
          ? p.basenameWithoutExtension(source)
          : p.basenameWithoutExtension(source);
      return _sanitizePathSegment(stem);
    }

    final now = DateTime.now();
    final stamp =
        '${now.year}${_two(now.month)}${_two(now.day)}_${_two(now.hour)}${_two(now.minute)}${_two(now.second)}';
    return 'Selected Files $stamp';
  }

  static String _two(int value) => value.toString().padLeft(2, '0');

  static String _sanitizePathSegment(String value) {
    final sanitized = value
        .replaceAll(RegExp(r'[\\/:*?"<>|]+'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
    if (sanitized.isEmpty || sanitized == '.' || sanitized == '..') {
      return 'Imported Files';
    }
    return sanitized;
  }

  static String? _safeArchiveEntryPath(String rawName) {
    var normalized = rawName.replaceAll('\\', '/').trim();
    if (normalized.isEmpty) return null;
    if (normalized.startsWith('/')) return null;
    normalized = p.posix.normalize(normalized);
    if (normalized.isEmpty ||
        normalized == '.' ||
        normalized == '..' ||
        normalized.startsWith('../') ||
        RegExp(r'^[a-zA-Z]:').hasMatch(normalized)) {
      return null;
    }

    final parts = normalized
        .split('/')
        .where((part) => part.isNotEmpty && part != '.')
        .toList(growable: false);
    if (parts.isEmpty || parts.any((part) => part == '..')) return null;
    return p.joinAll(parts.map(_sanitizePathSegment).toList());
  }

  static Future<Directory> _uniqueDirectory(
    String parentPath,
    String preferredName,
  ) async {
    final baseName = _sanitizePathSegment(preferredName);
    var candidate = p.join(parentPath, baseName);
    var suffix = 2;
    while (await FileSystemEntity.type(candidate) !=
        FileSystemEntityType.notFound) {
      candidate = p.join(parentPath, '$baseName $suffix');
      suffix += 1;
    }
    return Directory(candidate)..createSync(recursive: true);
  }

  static Future<String> _uniqueFilePath(String desiredPath) async {
    var candidate = desiredPath;
    final dir = p.dirname(desiredPath);
    final ext = p.extension(desiredPath);
    final stem = p.basenameWithoutExtension(desiredPath);
    var suffix = 2;
    while (await FileSystemEntity.type(candidate) !=
        FileSystemEntityType.notFound) {
      candidate = p.join(dir, '$stem $suffix$ext');
      suffix += 1;
    }
    return candidate;
  }

  static bool _isPathWithin(String parentPath, String childPath) {
    final parent = p.normalize(p.absolute(parentPath));
    final child = p.normalize(p.absolute(childPath));
    if (child == parent) return true;
    final relative = p.relative(child, from: parent);
    return relative != '..' && !relative.startsWith('..${p.separator}');
  }
}

class _CopyResult {
  const _CopyResult({
    required this.files,
    required this.wasRenamed,
  });

  final List<ImportedFileRecord> files;
  final bool wasRenamed;
}

class _ZipExtractResult {
  const _ZipExtractResult({
    required this.files,
    required this.renamedConflictCount,
    required this.skippedUnsafeArchiveEntries,
  });

  final List<ImportedFileRecord> files;
  final int renamedConflictCount;
  final int skippedUnsafeArchiveEntries;
}
