import 'dart:async';
import 'dart:collection';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:memex/utils/logger.dart';
import 'package:photo_manager/photo_manager.dart';

typedef PhotoThumbnailLoader = Future<Uint8List?> Function(
  AssetEntity asset,
  ThumbnailSize size,
  PMCancelToken cancelToken,
);

typedef PhotoThumbnailCanceller = Future<void> Function(
  PMCancelToken cancelToken,
);

/// Builds a PhotoKit-compatible thumbnail request.
///
/// `photo_manager` waits for a non-degraded PhotoKit result before completing
/// the Dart future. Its current Apple implementation drops the cancel-token
/// mapping when opportunistic delivery emits a degraded frame, so use a single
/// final result to keep the native request cancellable for its whole lifetime.
@visibleForTesting
ThumbnailOption buildPhotoThumbnailOption(
  ThumbnailSize size, {
  required bool isApplePlatform,
}) {
  if (!isApplePlatform) return ThumbnailOption(size: size);
  return ThumbnailOption.ios(
    size: size,
    deliveryMode: DeliveryMode.highQualityFormat,
    resizeMode: ResizeMode.fast,
    resizeContentMode: ResizeContentMode.fill,
  );
}

/// A cancellable subscription to one shared thumbnail request.
class PhotoThumbnailRequest {
  PhotoThumbnailRequest._(this.future, this._onCancel);

  final Future<Uint8List?> future;
  final void Function() _onCancel;
  bool _cancelled = false;

  void cancel() {
    if (_cancelled) return;
    _cancelled = true;
    _onCancel();
  }
}

/// Bounds PhotoKit/MediaStore work generated by rapidly recycled grid cells.
///
/// Visible cells requesting the same asset share one native request. When the
/// last cell releases it, queued work is removed and active native work is
/// cancelled. Successful bytes are retained in a small LRU cache.
class PhotoThumbnailService {
  PhotoThumbnailService._({
    required PhotoThumbnailLoader loader,
    required PhotoThumbnailCanceller canceller,
    required int maxConcurrent,
    required int maxCacheEntries,
    required Duration requestTimeout,
  })  : assert(maxConcurrent > 0),
        assert(maxCacheEntries >= 0),
        _loader = loader,
        _canceller = canceller,
        _maxConcurrent = maxConcurrent,
        _maxCacheEntries = maxCacheEntries,
        _requestTimeout = requestTimeout;

  factory PhotoThumbnailService.forTesting({
    required PhotoThumbnailLoader loader,
    PhotoThumbnailCanceller? canceller,
    int maxConcurrent = 2,
    int maxCacheEntries = 8,
    Duration requestTimeout = const Duration(seconds: 1),
  }) {
    return PhotoThumbnailService._(
      loader: loader,
      canceller: canceller ?? (_) async {},
      maxConcurrent: maxConcurrent,
      maxCacheEntries: maxCacheEntries,
      requestTimeout: requestTimeout,
    );
  }

  static final PhotoThumbnailService instance = PhotoThumbnailService._(
    loader: _loadThumbnail,
    canceller: (token) => token.cancelRequest(),
    maxConcurrent: 8,
    maxCacheEntries: 160,
    requestTimeout: const Duration(seconds: 12),
  );

  final _logger = getLogger('PhotoThumbnailService');
  final PhotoThumbnailLoader _loader;
  final PhotoThumbnailCanceller _canceller;
  final int _maxConcurrent;
  final int _maxCacheEntries;
  final Duration _requestTimeout;
  final Queue<_PendingThumbnail> _queue = Queue<_PendingThumbnail>();
  final Map<String, _PendingThumbnail> _inFlight = {};
  final LinkedHashMap<String, Uint8List> _cache = LinkedHashMap();
  int _activeCount = 0;

  PhotoThumbnailRequest request(
    AssetEntity asset, {
    ThumbnailSize size = const ThumbnailSize.square(200),
  }) {
    final key = _keyFor(asset, size);
    final cached = _cache.remove(key);
    if (cached != null) {
      _cache[key] = cached;
      return PhotoThumbnailRequest._(Future.value(cached), () {});
    }

    var pending = _inFlight[key];
    if (pending == null) {
      pending = _PendingThumbnail(
        key: key,
        asset: asset,
        size: size,
        cancelToken: PMCancelToken(debugLabel: key),
      );
      pending.listeners = 1;
      _inFlight[key] = pending;
      _queue.add(pending);
      _pump();
    } else {
      pending.listeners += 1;
    }

    var released = false;
    return PhotoThumbnailRequest._(pending.completer.future, () {
      if (released) return;
      released = true;
      _release(pending!);
    });
  }

  void _release(_PendingThumbnail pending) {
    if (pending.listeners > 0) pending.listeners -= 1;
    if (pending.listeners > 0 || pending.cancelled) return;

    pending.cancelled = true;
    if (!pending.started) {
      _queue.remove(pending);
      _inFlight.remove(pending.key);
      if (!pending.completer.isCompleted) pending.completer.complete(null);
      return;
    }

    if (!pending.completer.isCompleted) pending.completer.complete(null);
    if (identical(_inFlight[pending.key], pending)) {
      _inFlight.remove(pending.key);
    }
    unawaited(_cancelNativeRequest(pending));
  }

  Future<void> _cancelNativeRequest(_PendingThumbnail pending) async {
    try {
      await _canceller(pending.cancelToken);
    } catch (e, st) {
      _logger.fine('Failed to cancel thumbnail ${pending.key}: $e', e, st);
    }
  }

  void _pump() {
    while (_activeCount < _maxConcurrent && _queue.isNotEmpty) {
      final pending = _queue.removeFirst();
      if (pending.cancelled) continue;
      pending.started = true;
      _activeCount += 1;
      unawaited(_run(pending));
    }
  }

  Future<void> _run(_PendingThumbnail pending) async {
    Uint8List? bytes;
    try {
      bytes = await _loader(
        pending.asset,
        pending.size,
        pending.cancelToken,
      ).timeout(_requestTimeout);
    } on TimeoutException catch (e, st) {
      pending.cancelled = true;
      unawaited(_cancelNativeRequest(pending));
      _logger.warning('Thumbnail timed out: ${pending.key}', e, st);
    } catch (e, st) {
      if (!pending.cancelled) {
        _logger.warning('Thumbnail failed: ${pending.key}', e, st);
      }
    } finally {
      if (!pending.cancelled && bytes != null && _maxCacheEntries > 0) {
        _cache[pending.key] = bytes;
        while (_cache.length > _maxCacheEntries) {
          _cache.remove(_cache.keys.first);
        }
      }
      if (!pending.completer.isCompleted) {
        pending.completer.complete(pending.cancelled ? null : bytes);
      }
      if (identical(_inFlight[pending.key], pending)) {
        _inFlight.remove(pending.key);
      }
      _activeCount -= 1;
      _pump();
    }
  }

  static String _keyFor(AssetEntity asset, ThumbnailSize size) {
    return '${asset.id}:${size.width}x${size.height}';
  }

  static Future<Uint8List?> _loadThumbnail(
    AssetEntity asset,
    ThumbnailSize size,
    PMCancelToken cancelToken,
  ) {
    final option = buildPhotoThumbnailOption(
      size,
      isApplePlatform: Platform.isIOS || Platform.isMacOS,
    );
    return asset.thumbnailDataWithOption(option, cancelToken: cancelToken);
  }
}

class _PendingThumbnail {
  _PendingThumbnail({
    required this.key,
    required this.asset,
    required this.size,
    required this.cancelToken,
  });

  final String key;
  final AssetEntity asset;
  final ThumbnailSize size;
  final PMCancelToken cancelToken;
  final Completer<Uint8List?> completer = Completer<Uint8List?>();
  int listeners = 0;
  bool started = false;
  bool cancelled = false;
}
